apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bd-ingress
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - itconnect.it.com
      secretName: bd-tls
  rules:
    - host: itconnect.it.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bd-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bd-frontend
                port:
                  number: 80
