services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: business-directory-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123!"
    ports:
      - "1433:1433"
    volumes:
      - bd_mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_strong_password123!' -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  bd_mssql_data:
