apiVersion: v1
kind: Service
metadata:
  name: business-directory-api
  labels:
    app: business-directory-api
spec:
  type: ClusterIP
  selector:
    app: business-directory-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
